#!/bin/bash

#We have a disk image of a Singularity container that has BioPerl installed module load singularity
#This uses script get_gb.pl to pull sequences from GenBank by accession numbers in testfile


#check if using galaxy-dev and change path of bioperl image using singularity
thehost=$(hostname)
if [ $thehost = "pod-login1.podcluster" ]; then
	sing_image="/home/pcw/ubuntu_bioperl_biopy2.img" 
fi
if [ $thehost = "galaxy-dev" ]; then
        echo Using host: $thehost
	sing_image="ubuntu_bioperl_biopy2.img" 

fi

accdir="data/accessions"
seqdir="data/sequences"

#singularity exec $sing_image perl scripts/get_gb.pl $accdir/yoo_et_al_2019_its.txt nucleotide phytab $seqdir/yoo_et_al_2019_its.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/brandao_et_al_2010_co1.txt nucleotide phytab $seqdir/brandao_et_al_2010_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/brandao_et_al_2010_its.txt nucleotide phytab $seqdir/brandao_et_al_2010_its.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/gandolfi_et_al_2001_its1.txt nucleotide phytab $seqdir/gandolfi_et_al_2001_its1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/hiruta_et_al_2016a_18s.txt nucleotide phytab $seqdir/hiruta_et_al_2016a_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/hiruta_et_al_2016a_28s.txt nucleotide phytab $seqdir/hiruta_et_al_2016a_28s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/hiruta_et_al_2016b_co1.txt nucleotide phytab $seqdir/hiruta_et_al_2016b_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic__et_al_2015_co1.txt nucleotide phytab $seqdir/karanovic__et_al_2015_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic_et_al_2016_18s.txt nucleotide phytab $seqdir/karanovic_et_al_2016_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic_et_al_2017a_16s.txt nucleotide phytab $seqdir/karanovic_et_al_2017a_16s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic_et_al_2017a_18s.txt nucleotide phytab $seqdir/karanovic_et_al_2017a_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic_et_al_2017a_28s.txt nucleotide phytab $seqdir/karanovic_et_al_2017a_28s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic_et_al_2017b_18s.txt nucleotide phytab $seqdir/karanovic_et_al_2017b_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic_et_al_2017b_28s.txt nucleotide phytab $seqdir/karanovic_et_al_2017b_28s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic_et_al_2017b_co1.txt nucleotide phytab $seqdir/karanovic_et_al_2017b_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/kong_et_al_2014_18s.txt nucleotide phytab $seqdir/kong_et_al_2014_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/martens_2005_co1.txt nucleotide phytab $seqdir/martens_2005_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/martens_2005_its1.txt nucleotide phytab $seqdir/martens_2005_its1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/nigro_et_al_2016_co1.txt nucleotide phytab $seqdir/nigro_et_al_2016_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/rossi_et_al._2007_16s_rrna.txt nucleotide phytab $seqdir/rossi_et_al._2007_16s_rrna.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_1998_co1.txt nucleotide phytab $seqdir/schon_1998_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_1998_its1.txt nucleotide phytab $seqdir/schon_1998_its1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2012_co1.txt nucleotide phytab $seqdir/schon_2012_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2012_its1.txt nucleotide phytab $seqdir/schon_2012_its1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2015_co1.txt nucleotide phytab $seqdir/schon_2015_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2017_16s.txt nucleotide phytab $seqdir/schon_2017_16s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2017_28s.txt nucleotide phytab $seqdir/schon_2017_28s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_et_al_2003_co1.txt nucleotide phytab $seqdir/schon_et_al_2003_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_et_al_2003_its1.txt nucleotide phytab $seqdir/schon_et_al_2003_its1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_et_al_2018_co1.txt nucleotide phytab $seqdir/schon_et_al_2018_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_et_al_2018_ef1a.txt nucleotide phytab $seqdir/schon_et_al_2018_ef1a.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_halse_et_al_2017_co1.txt nucleotide phytab $seqdir/schon_halse_et_al_2017_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_halse_et_al_2017_its1.txt nucleotide phytab $seqdir/schon_halse_et_al_2017_its1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/tanaka_and_ohtsuka_2016_co1.txt nucleotide phytab $seqdir/tanaka_and_ohtsuka_2016_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/tanaka_et_al_2014_its.txt nucleotide phytab $seqdir/tanaka_et_al_2014_its.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/tanaka_et_al_2016_co1.txt nucleotide phytab $seqdir/tanaka_et_al_2016_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/wysocka_et_al_2019_co1.txt nucleotide phytab $seqdir/wysocka_et_al_2019_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/xu_et_al_2018_co1.txt nucleotide phytab $seqdir/xu_et_al_2018_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/xu_et_al_2019_co1.txt nucleotide phytab $seqdir/xu_et_al_2019_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/yamaguchi_et_al_2003_18s.txt nucleotide phytab $seqdir/yamaguchi_et_al_2003_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/yoo_et_al_2016_18s.txt nucleotide phytab $seqdir/yoo_et_al_2016_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/yoo_et_al_2016_28s.txt nucleotide phytab $seqdir/yoo_et_al_2016_28s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/yoo_et_al_2019_18s.txt nucleotide phytab $seqdir/yoo_et_al_2019_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/yoo_et_al_2019_co1.txt nucleotide phytab $seqdir/yoo_et_al_2019_co1.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/yu_et_al_2006_18s.txt nucleotide phytab $seqdir/yu_et_al_2006_18s.phytab '' '' firstline
#singularity exec $sing_image perl scripts/get_gb.pl $accdir/yu_et_al_2018_18s.txt nucleotide phytab $seqdir/yu_et_al_2018_18s.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/Estronza_2017_28S.txt nucleotide phytab $seqdir/Estronza_2017_28S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/Karanovic_2015_18S.txt nucleotide phytab $seqdir/Karanovic_2015_18S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/Karanovic_2015_28S.txt nucleotide phytab $seqdir/Karanovic_2015_28S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/Karanovic_2015_CO1.txt nucleotide phytab $seqdir/Karanovic_2015_CO1.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/karanovic_2016b_28S.txt nucleotide phytab $seqdir/karanovic_2016b_28S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/Karanovic_2017c_16S.txt nucleotide phytab $seqdir/Karanovic_2017c_16S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/Karanovic_2017c_18S.txt nucleotide phytab $seqdir/Karanovic_2017c_18S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/Karanovic_2017c_28S.txt nucleotide phytab $seqdir/Karanovic_2017c_28S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/Karanovic_2017c_CO1.txt nucleotide phytab $seqdir/Karanovic_2017c_CO1.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2000_CO1.txt nucleotide phytab $seqdir/schon_2000_CO1.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2000_ITS1.txt nucleotide phytab $seqdir/schon_2000_ITS1.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2014_16S.txt nucleotide phytab $seqdir/schon_2014_16S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2014_28S.txt nucleotide phytab $seqdir/schon_2014_28S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/schon_2014_ITS.txt nucleotide phytab $seqdir/schon_2014_ITS.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/tanaka_2014b_18S.txt nucleotide phytab $seqdir/tanaka_2014b_18S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/wakayama_2006_16S.txt nucleotide phytab $seqdir/wakayama_2006_16S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/zhang_2003_18S.txt nucleotide phytab $seqdir/zhang_2003_18S.phytab '' '' firstline
singularity exec $sing_image perl scripts/get_gb.pl $accdir/zhang_2003_28S.txt nucleotide phytab $seqdir/zhang_2003_28S.phytab '' '' firstline








