#!/bin/bash

#We have a disk image of a Singularity container that has BioPerl installed module load singularity
#This uses script get_gb.pl to pull sequences from GenBank by accession numbers in testfile

sing_image="/home/pcw/ubuntu_bioperl_biopy2.img" 
accdir="data/accessions"
seqdir="data/sequences"

singularity exec $sing_image perl scripts/get_gb.pl $accdir/yoo_et_al_2019_its.txt nucleotide phytab $seqdir/yoo_et_al_2019_its.phytab '' '' firstline

