#!/bin/bash

#We have a disk image of a Singularity container that has BioPerl installed module load singularity
#This uses script get_gb.pl to pull sequences from GenBank by accession numbers in testfile

sing_image="/home/pcw/ubuntu_bioperl_biopy2.img" 
accdir="data/accessions"
seqdir="data/sequences"
tdir="data/transcriptomes"
andir="analyses"

cat $seqdir/*.phytab $tdir/oakley_2013_?8S.phytab > $andir/all_genbank.phytab


#Convert line breaks to unix in case they were from Windows
dos2unix $andir/all_genbank.phytab


perl scripts/remove_acc.pl $andir/all_genbank.phytab Accessions_to_be_removed.txt $andir/all_genbank_k.phytab $andir/all_genbank_d.phytab 
perl scripts/remove_phytab_dupes.pl $andir/all_genbank_k.phytab 1 1 $andir/uni_genbank.phytab $andir/dupe_genbank.phytab


#Uncomment to align all sequences. Takes time, so commenting here to allow rerunning other parts
rm -r tmpphytabdata #remove directory created by phytab_muscle

#./scripts/phytab_muscle.py -i analyses/uni_genbank.phytab
#Now call slurm for alignment instead of head node
sbatch scripts/phymus_slurm.sh analyses/uni_genbank.phytab

